name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create dist Directory
        run: mkdir -p dist

      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: lucasA51
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Check Generated Files
        run: ls -lah dist  # Debugging step

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
          clean: true
